version: '3'


services:
  app:
    build: .
    container_name: app-backend
    volumes:
      - ./migrations:/app/migrations
      - ./env:/app/env
    ports:
      - "9000:50050"
    depends_on:
      - db
    networks:
      - myloc
  db:
    image: postgres
    container_name: db_app
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: zxcMentor
      POSTGRES_NAME: postgres
    ports:
      - "127.0.0.1:54321:5432"
    networks:
      - myloc

networks:
  myloc:
    driver: bridge