version: '3'


services:
  app:
    build: .
    container_name: app_backend
    volumes:
      - ./migrations:/app/migrations
      - ./.env:/app/.env
    ports:
      - "9000:50050"
      - "2121:2121"
    depends_on:
      - db
      - tj
    networks:
      - myloc
  db:
    image: postgres
    container_name: db_app
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: zxcMentor
      POSTGRES_NAME: postgres
    ports:
      - "127.0.0.1:54321:5432"
    networks:
      - myloc
  tj:
    image: jaegertracing/all-in-one
    container_name: tj_app
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - myloc
  pr:
    image: prom/prometheus
    container_name: pr_app
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - myloc

networks:
  myloc:
    driver: bridge